### PR TITLE
Got bored. Did a make over for the README.

### PR DESCRIPTION
**Pull request by Lazylllama**
Alright. The screenshots will be replaced with something proper once i get my hands on the iphone 14 bezels. Stupid apple saves them in .dmg format so only apple users can use them 👿 

Well hope ya like it and also. check the number 1 in the roadmap checklist.

### CODE REVIEW

**Review by SoloUnity — APPROVED** [review]

**Comment by Lazylllama** [comment]
Wierd.

**Comment by Lazylllama** [comment]
The only file i changed in this pull is the README.md

**Comment by SoloUnity** [comment]
Whoops I just had to dismiss my review, nothing is actually wrong

**Comment by Lazylllama** [comment]
> Whoops I just had to dismiss my review, nothing is actually wrong

Gotcha

**Review by SoloUnity — APPROVED** [review]

**Pull request merged**
